// app\layout.tsx

// @ts-ignore
import type { Metadata } from "next";
// @ts-ignore
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "./ui/common/header/header";
import Footer from "./ui/common/footer/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body suppressHydrationWarning={true} className={`${inter.className}`}>
            <Header />
            <div className="">
                {children}
            </div>
            <Footer />
        </body>
    </html>
  );
}
